name: Build and Push Docker Image
on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: vk887
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKER_USERNAME/v-python-app .
          docker push $DOCKER_USERNAME/v-python-app
